export const marketplaceCategories = [
  "Electronics",
  "Fashion",
  "Home & Garden",
  "Automotive",
  "Sports & Outdoors",
  "Health & Beauty",
  "Toys & Hobbies",
  "Books",
  "Movies & Music",
  "Real Estate",
  "Services",
  "Pets & Animals",
  "Food & Beverage",
  "Collectibles & Art",
  "Industrial & Scientific",
  "Office Supplies",
  "Baby & Kids",
  "Travel & Events",
  "Crafts & Handmade",
  "Software & Games",
];
