import ".././globals.css";
import NextAuthSessionProvider from "../nextAuthSessionProvider";

export const metadata = {
  title: "onboarding",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className=" h-full w-full bg-[url(/jpeg/waveBg.jpg)] bg-blend-overlay">
      {children}
    </section>
  );
}
