"use client";
import { usePathname } from "next/navigation";

const path = usePathname();
export const metadata = {
  title: path === "/login" ? "Login" : "Register",
  description: "Generated by Next.js",
};
